---
  paths:
    access_log: /var/log/nginx/mailee_view.log
    click_log: /var/log/nginx/mailee_click.log
  database:
    host: localhost
    port: 5432
    dbname: mailee_test
    user: log_watcher
    password: 1234
    
